return {
    Normal = {
        Visible = {
            Minimum = 0, 
            Maximum = 25
        },
        Dotted = {
            Minimum = 26,
            Maximum = 50
        },
        Hide = {
            Minimum = 51,
            Maximum = 400
        }
    },

    Yell = {
        Visible = {
            Minimum = 0, 
            Maximum = 25
        },
        Dotted = {
            Minimum = 26,
            Maximum = 50
        },
        Hide = {
            Minimum = 51,
            Maximum = 700
        }
    },
}